name: GriefPreventionCui
version: ${project.version}
main: at.haha007.griefpreventioncui.GriefPreventionCui
api-version: 1.17
depend: [GriefPrevention]
authors: [Haha007]
description: Client user interface for Griefprevention Claims
